# Generated by Django 5.0.6 on 2024-06-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade_disponivel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cusro', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('devolvido', 'Devolvido')], default='pendente', max_length=10)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.usuario')),
            ],
        ),
    ]
