# Generated by Django 5.0.6 on 2024-06-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cusro',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='mome',
            new_name='nome',
        ),
    ]
